# Generated by Django 5.1.3 on 2025-09-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_join', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_query', models.TextField(help_text='Original natural language query')),
                ('generated_sql', models.TextField(help_text='Generated SQL query')),
                ('success', models.BooleanField(help_text='Whether query was successful')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time', models.FloatField(help_text='Query execution time in seconds')),
                ('result_count', models.IntegerField(default=0, help_text='Number of results returned')),
                ('cached', models.BooleanField(default=False, help_text='Whether result was cached')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'query_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
